### ISSUE TITLE
iOS build freeze

### ISSUE THREAD

**Issue by peterpeterparker** [dpa99c/cordova-plugin-firebase#5]
**Describe the bug**
Hi Dave,

I installed the plugin as described in your comment in (https://github.com/arnesson/cordova-plugin-firebase/issues/1081#issuecomment-503135862).

With Android, all good, it works like a charm.

With iOS, on the other side, I'm not able to compile/build the app with the command line once I had this plugin to my app.

I use Cordova v9 and NodeJS v12

I tried many times to remove and add platforms and plugins but I always land on the same problem, when I run `ionic cordova build ios` the build will always freeze respectively it will hang on the following:

> ProcessPCH /Users/myProject/platforms/ios/build/sharedpch/SharedPrecompiledHeaders/10438514788408785055/MyApp-Prefix.pch.gch /Users/myProject/platforms/ios/MyApp/MyApp-Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: MyApp)
> cd /Users/myProject/platforms/ios
>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x .... (a lot of lines) ... 8408785055/MyApp-Prefix.pch.dia

Interesting, if I abort the build and open the project in Xcode v10.2.1 I'm able to build the project in Xcode without any problem.

I also tried many times to reboot my laptop (Mac) thinking that maybe a process would remains blocker but nothing helped.

I'm not sure it's directly related to the plugin, maybe it's related to Cordova v9(?), but I definitely don't face it when I remove the plugin.

I'm aware it isn't probably an issue and most probably more a support question so I hope you will accept my apologies for that. Of course if you don't face the problem and would close the issue without any comment, that would be absolutely no problem.

Thx for all your cool work and again for your about the other issue of today!

P.S.: A sample repo to reproduce the problem

https://github.com/peterpeterparker/ios-build-freeze

**Comment by peterpeterparker** [comment]
Note, don't know if this is related but I do see the following warning at the begin of the build:

> Pod installation complete! There are 7 dependencies from the Podfile and 19 total pods installed.
> 
> 
> [!] The `MyApp [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Circle/Pods-Circle.debug.xcconfig'. This can lead to problems with the CocoaPods installation
> 
> [!] The `MyApp [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Circle/Pods-Circle.release.xcconfig'. This can lead to problems with the CocoaPods installation
> 
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.

**Comment by dann95** [comment]
can you post config.xml plugins and package.json ?

**Comment by peterpeterparker** [comment]
@dann95 sure. I was able to reproduce the problem in a sample minimal project, here's the repo:

https://github.com/peterpeterparker/ios-build-freeze

**Comment by Hanzofm** [comment]
Same problem:

**Comment by dpa99c** [comment]
Will look into this today

**Comment by dpa99c** [comment]
I've tried to reproduce this issue in an isolated test case using the following commands:

	cordova create test io.cordova.firebase.test && cd test
	curl https://raw.githubusercontent.com/dpa99c/cordova-plugin-firebase-test/master/www/GoogleService-Info.plist -o GoogleService-Info.plist
	cordova platform add ios@latest
	cordova plugin add cordova-plugin-firebasex
	# edit open project in Xcode and set development team
	cordova build ios --device


But the build succeeds: [console log](https://www.dropbox.com/s/6brep2m8yc5q2z5/log.txt?dl=0)

Please try the above commands in your environment and report the result.

**Comment by peterpeterparker** [comment]
thx @dpa99c 

I could confirm that using the exact same commands as you I don't face the problem neither

On the other side when I do try out again the sample repo I provided in a fresh install I still face the error

Incompatibility with another plugin maybe?

**Comment by Hanzofm** [comment]
What do this?

`curl https://raw.githubusercontent.com/dpa99c/cordova-plugin-firebase-test/master/www/GoogleService-Info.plist -o GoogleService-Info.plist`

**Comment by dpa99c** [comment]
@Hanzofm it downloads a dummy iOS configuration file for the Firebase plugin.
Not sure if iOS build fails without it, but Android certainly does.

**Comment by dpa99c** [comment]
@peterpeterparker I'll clone your sample repo and investigate

**Comment by peterpeterparker** [comment]
thx a lot Dave for all your effort!

**Comment by dpa99c** [comment]
Some interesting results when testing with your project.

So I did:

	git clone https://github.com/peterpeterparker/ios-build-freeze && cd ios-build-freeze
	npm install
	ionic cordova platform add ios@latest
	ionic cordova build ios

And in this case I can replicate your observed results: the build command hangs on the `clang` step.

But if I do the same and instead use the Cordova (instead of Ionic) CLI to build, it doesn't hang and builds OK:

	git clone https://github.com/peterpeterparker/ios-build-freeze && cd ios-build-freeze
	npm install
	ionic cordova platform add ios@latest
	ionic cordova prepare ios
	cordova build ios

And if I remove `cordova-plugin-firebasex` it builds OK with the Ionic CLI:

	git clone https://github.com/peterpeterparker/ios-build-freeze && cd ios-build-freeze
	npm install
	cordova plugin rm cordova-plugin-firebasex
	ionic cordova platform add ios@latest
	ionic cordova build ios

I've no idea why it hangs with Ionic CLI and not Cordova but my recommendation would to be repeat my tests above and if it works OK using ionic CLI to prepare the platform and cordova CLI to build it, then go with this as a workaround for now.

**Comment by peterpeterparker** [comment]
excellent @dpa99c I'm agree and could confirm with your finding. For now one the following target/workaround does the job:

```
"scripts": {
      "ios": "ionic cordova prepare ios --prod && cordova build ios"
}
```

Should we ping the Ionic-cli repo?

**Comment by dpa99c** [comment]
> Should we ping the Ionic-cli repo?

it does seem related to Ionic so might be worth opening an issue there and linking to this one

**Comment by peterpeterparker** [comment]
Agree @dpa99c 

I have opened and issue in the Ionic CLI repo (https://github.com/ionic-team/ionic-cli/issues/4042) and therefore I close this issue. If you would follow the issue I would honestly don't mind ;)

Thx again for your great plugins and support 👍

**Comment by dpa99c** [comment]
a quick update: 
I just tried the experiment again but this time installing the plugin direct from the git repo which contains an update to use `<pod>` instead of `<framework type="podspec">` and the build succeeded with Ionic. Please try the following to see if you can confirm. If so I will publish the repo as a new plugin version.


	git clone https://github.com/peterpeterparker/ios-build-freeze && cd ios-build-freeze
	npm install
	cordova plugin rm cordova-plugin-firebasex
	cordova plugin add https://github.com/dpa99c/cordova-plugin-firebase.git #this took a while to install
	ionic cordova platform add ios@latest
	ionic cordova build ios

**Comment by peterpeterparker** [comment]
Awesome @dpa99c ! I confirm that it solves the issue, I was able to build my app (I skipped the sample repo and tried it directly in my app) using `master` branch of the plugin

Thx a lot!

**Comment by dpa99c** [comment]
I've published the current master branch of this plugin as `cordova-plugin-firebasex@2.0.7`

**Comment by peterpeterparker** [comment]
It works like a charm, thx a lot @dpa99c  !

**Comment by Hanzofm** [comment]
what is solved in 2.0.7?

**Comment by dann95** [comment]
> what is solved in 2.0.7?

the generated Podfile.

**Comment by Hanzofm** [comment]
Then, now is possible to install normally?

**Comment by peterpeterparker** [comment]
Yes

**Comment by remifleurance** [comment]
Hello,
I have the exact same issue using the latest 2.1.2 version.

From the command line it hangs on : 
> [..] MyApp-Prefix.pch.dia

Opening and building on Xcode gives me the follow error :
![Screen Shot 2019-06-21 at 16 17 34](https://user-images.githubusercontent.com/49188782/59928025-2029bc00-943e-11e9-9375-df3d12c48874.png)

So it seems to be still related to CocoaPods

**Comment by peterpeterparker** [comment]
@remifleurance  maybe open a new issue?

I'm (still) good and mine was solved with v2.0.7 of the plugin, so maybe something changed since then

**Comment by dpa99c** [comment]
@remifleurance I just tried the following test with v2.1.2 and the iOS build succeeded:


	ionic start test blank --cordova --package-id=cordova.plugins.diagnostic.example && cd test
	ionic cordova plugin add cordova-plugin-firebasex
	ionic cordova platform add ios@latest
	ionic cordova build ios

Please try the same in your environment.

Note: I used package ID `cordova.plugins.diagnostic.example` because it's one for which I have a provisioning profile installed which supports push notifications, so you may need to use a different package name.

**Comment by remifleurance** [comment]
Thanks for you answers

@peterpeterparker I tried with 2.0.7 too, but the issue is still there

@dpa99c I gave it a try using my own package ID
> ionic cordova build ios

is not freezing anymore. But I still have the same error on Xcode.

I'm using Xcode 10.1, Node 10.15.3 and Cordova 9.0.0

**Comment by remifleurance** [comment]
Ok, after trying different things I was able to solve this issue.
*FirebaseCore/FirebaseCore.h* was located in Pods folder.

So in Xcode I went to :
> General tab > Linked Frameworks and Libraries

and opened **Pods/Pods.xcodeproj**
Doing so allowed Xcode to add all files prepared by Cocoapods.

Not sure if this is how *Pods.xcodeproj* is supposed to be included ?

**Comment by dpa99c** [comment]
If you open `YourProject.xcworkspace` (instead of `YourProject.xcodeproj`) in Xcode, both your Cordova app project and the Pods project will be loaded into Xcode.

**Comment by remifleurance** [comment]
Oh ok. I'm a beginner in Xcode, Cocoapods etc...
Thanks for this information

**Comment by JohnMokgokong** [comment]
@dpa99c Hi, we have the same issue as this  iOS build freeze #5
we have tried the solutions in the comments, unfortunately, none of them work in our case please help

ionic info

**Comment by testanddeploy** [comment]
I am facing the same problem.

I am using 
cordova-plugin-firebasex 3.0.8 "Google Firebase Plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"

With this config I am be able to ios build in other projects  but in this specific project no.(build via xCode works fine)


this is my pod outdated list

- Crashlytics 3.12.0 -> 3.12.0 (latest version 3.13.4)
- Fabric 1.9.0 -> 1.9.0 (latest version 1.10.2)
- Firebase 6.3.0 -> (unused) (latest version 6.5.0)
- FirebaseAnalytics 6.0.2 -> 6.0.2 (latest version 6.0.4)
- FirebaseAuth 6.1.2 -> 6.1.2 (latest version 6.2.1)
- FirebaseCore 6.0.3 -> 6.0.3 (latest version 6.1.0)
- FirebasePerformance 3.1.0 -> 3.1.0 (latest version 3.1.1)
- FirebaseRemoteConfig 4.1.0 -> 4.1.0 (latest version 4.2.1)
- GoogleAppMeasurement 6.0.2 -> 6.0.2 (latest version 6.0.4)
- GoogleMaps 2.7.0 -> 2.7.0 (latest version 3.2.0)


I have installed @angular/fire and firebase 6.3.1 npm libraries

Any idea?

**Comment by afelipelli** [comment]
> I am facing the same problem freezes in:
> 
> `/myProject/platforms/ios/build/sharedpch/SharedPrecompiledHeaders/5415175148216068724/myProject-Prefix.pch.dia`
> 
> I am using
> cordova-plugin-firebasex 3.0.8 "Google Firebase Plugin"
> cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
> cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
> 
> With this config I am be able to ios build in other projects but in this specific project no.(build via xCode works fine)
> 
> this is my pod outdated list
> 
> * Crashlytics 3.12.0 -> 3.12.0 (latest version 3.13.4)
> * Fabric 1.9.0 -> 1.9.0 (latest version 1.10.2)
> * Firebase 6.3.0 -> (unused) (latest version 6.5.0)
> * FirebaseAnalytics 6.0.2 -> 6.0.2 (latest version 6.0.4)
> * FirebaseAuth 6.1.2 -> 6.1.2 (latest version 6.2.1)
> * FirebaseCore 6.0.3 -> 6.0.3 (latest version 6.1.0)
> * FirebasePerformance 3.1.0 -> 3.1.0 (latest version 3.1.1)
> * FirebaseRemoteConfig 4.1.0 -> 4.1.0 (latest version 4.2.1)
> * GoogleAppMeasurement 6.0.2 -> 6.0.2 (latest version 6.0.4)
> * GoogleMaps 2.7.0 -> 2.7.0 (latest version 3.2.0)
> 
> I have installed @angular/fire and firebase 6.3.1 npm libraries
> 
> Any idea?

Did you find any solution? I'm using cordova-plugin-firebasex 6.0.2 (latest) and still getting this hang when running ionic cordova build ios --prod

**ionic info:**
Ionic:

   Ionic CLI          : 5.2.3 (/Users/afelipel/.npm-global/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 18 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.16.0 (/usr/local/Cellar/node@10/10.16.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8

**cordova plugin list**

cc.fovea.cordova.purchase 7.4.3 "Purchase"
com.synconset.imagepicker 2.1.8 "ImagePicker"
cordova-admobsdk 7.37.0 "Google Mobile Ads SDK for Cordova"
cordova-launch-review 3.1.1 "Launch Review"
cordova-plugin-admobpro 2.37.2 "AdMob Plugin Pro"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-facebook4 2.5.0 "Facebook Connect"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.5.5 "cordova-plugin-filepath"
cordova-plugin-firebasex 6.0.2 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1-dev "Geolocation"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
cordova-sqlite-storage 3.1.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"

**Comment by auron105** [comment]
same problem in ios 5.0.1
ios 4.5.5 is work. 
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 12 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 8.0.1
   NodeJS     : v10.16.1 (/usr/local/bin/node)
   npm        : 6.10.2
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8

**Comment by Roman8817** [comment]
Same issue. ionic Cordova build on iOS is freeze on ProcessPCH

**Comment by elaval** [comment]
I am having a similar problem (freezing at Prefix.pch.dia) and noticed that it occurs if I do the build with an iPhone connected to the computer.  If I disconnect it, and start the build from scratch, the it ends OK.

**Comment by alexdelgado** [comment]
I'm having the same issue using `cordova-plugin-firebasex@6.0.2`

**Comment by rolinger** [comment]
I was running v6.0.7 but the `ionic cordova build iOS` simply, and cleanly, exited at `Preparing Firebase on iOS` - and no build files were actually created.  So I downgraded to v6.0.6 and now I too am getting the freezing at `myApp-Prefix.pch.dia` point in the build.  But this is only happening on iOS.  I was successfully able to build and deploy my app on Android using v6.0.7.

**Comment by abomadi** [comment]
I have the same issue also without attaching an iphone

**Comment by afelipelli** [comment]
In case it helps someone: I restarted my mac and it was working fine until I had the same issue again. Then I restarted the shell (terminal) and it built fine. I can't really explain it but thought I'd give the tip.

**Comment by rolinger** [comment]
@afelipelli - I will try that out.  How long did it work until it hung each time?  

Obviously something is up with this build of firebasex...its annoying.

**Comment by dwieeb** [comment]
👋 For those using the Ionic CLI, I just released 5.3.0 with a fix for this. See [CHANGELOG.md](https://github.com/ionic-team/ionic-cli/blob/develop/packages/ionic/CHANGELOG.md#530-2019-09-18). Please feel free to let me know if there are other issues! 

```
npm i -g ionic@latest
```

**Comment by brownoxford** [comment]
@dpa99c, @dwieeb With the latest 5.3.0 version of Ionic CLI I'm seeing success with `ionic cordova build ios --debug --device`, so there is some improvement, but I'm definitely still seeing some other issues when `cordova-plugin-firebasex` is installed - here is my test procedure:

### Create Base Project
```bash
ionic start pch-hang-test-base blank --type=ionic-angular && cd pch-hang-test-base
ionic cordova platform add ios
cd ..
```

### Test `ionic cordova build` (no firebasex) -> SUCCESS
```bash
cp -a pch-hang-test-base pch-hang-test-nofb-build && cd pch-hang-test-nofb-build
sed -i '' 's/io.ionic.starter/io.my.app/' config.xml # For signing config
ionic cordova build ios --debug --device \
  -- --packageType=development --developmentTeam=RN4LLP68J6
cd -
```

### Test `ionic cordova prepare/compile` (no firebasex) -> SUCCESS
```bash
cp -a pch-hang-test-base pch-hang-test-nofb-prep-comp && cd pch-hang-test-nofb-prep-comp
sed -i '' 's/io.ionic.starter/io.my.app/' config.xml # For signing config
ionic cordova prepare ios --debug --device
ionic cordova compile ios --debug --device \
  -- --packageType=development --developmentTeam=RN4LLP68J6
cd -
```

### Test `ionic cordova build` (with firebasex) -> SUCCESS
```bash
cp -a pch-hang-test-base pch-hang-test-fb-build && cd pch-hang-test-fb-build
ionic cordova plugin add cordova-plugin-firebasex
sed -i '' 's/io.ionic.starter/io.my.app/' config.xml # For signing config
ionic cordova build ios --debug --device \
  -- --packageType=development --developmentTeam=RN4LLP68J6
cd -
```

### Test `ionic cordova prepare/compile` (with firebasex) -> HANGS
```bash
cp -a pch-hang-test-base pch-hang-test-fb-prep-comp && cd pch-hang-test-fb-prep-comp
ionic cordova plugin add cordova-plugin-firebasex
sed -i '' 's/io.ionic.starter/io.my.app/' config.xml # For signing config
ionic cordova prepare ios --debug --device
ionic cordova compile ios --debug --device \
  -- --packageType=development --developmentTeam=RN4LLP68J6
cd -
```

### Ionic Environment
```
$ cd pch-hang-test-fb-prep-comp
$ ionic info

Ionic:

   Ionic CLI          : 5.3.0 (/Users/cabernet/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/Users/cabernet/.nvm/versions/node/v10.16.3/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8
```

**Comment by brownoxford** [comment]
This has been fixed in Ionic CLI 5.4.1 by https://github.com/ionic-team/ionic-cli/commit/44697cf4ebc77c656ac664c2ee08bcba052892af

**Comment by brenobarnard** [comment]
That's not for reopening, it's just to fix a @brownoxford mistake, the correct version of the fix are 5.4.12, not 5.4.1...
